# Generated by Django 3.2 on 2021-06-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestThreeBackupHistory',
            new_name='PeakBackupHistory',
        ),
        migrations.RenameModel(
            old_name='ValueAdjustHistory',
            new_name='PriceAdjustHistory',
        ),
        migrations.AlterField(
            model_name='powerplantsuppporthistory',
            name='time',
            field=models.DateTimeField(unique=True),
        ),
    ]
