# Generated by Django 3.2 on 2021-06-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210623_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='peakbackuphistory',
            name='time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='peakbackupthisyear',
            name='time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='peaksupportdemandhistory',
            name='time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='powerplantsuppporthistory',
            name='time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='priceadjusthistory',
            name='time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usagebycategory',
            name='time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usagestatistichistory',
            name='time',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
    ]
