# Generated by Django 3.2 on 2021-06-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20210623_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageByLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='peaksupportdemandhistory',
            name='powerplant',
            field=models.ManyToManyField(to='analysis.PowerPlantSuppportHistory'),
        ),
    ]
