# Generated by Django 3.2 on 2021-06-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_remove_peaksupportdemandhistory_powerplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='peaksupportdemandhistory',
            name='powerplant',
            field=models.ManyToManyField(blank=True, to='analysis.PowerPlantSuppportHistory'),
        ),
    ]
