# Generated by Django 3.2 on 2021-06-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_peaksupportdemandhistory_powerplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerplantsuppporthistory',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='powerplantsuppporthistory',
            unique_together={('time', 'name')},
        ),
    ]
