# Generated by Django 3.2 on 2021-06-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20210623_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeakBackupHistory',
            new_name='YearlyPeakBackupHistory',
        ),
    ]
